# Generated by Django 2.0.5 on 2018-06-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Pet_Type'),
        ),
    ]
