# Generated by Django 2.0.5 on 2018-06-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180605_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet_breed',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='pet_owner_interest_ref',
            name='interest_id',
        ),
        migrations.RemoveField(
            model_name='pet_owner_interest_ref',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet_parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='search',
            name='pet_breed_type',
        ),
        migrations.RemoveField(
            model_name='search',
            name='pet_type',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Pet_Breed',
        ),
        migrations.DeleteModel(
            name='Pet_Owner_Interest_Ref',
        ),
        migrations.DeleteModel(
            name='Pet_Owner_Interests',
        ),
        migrations.DeleteModel(
            name='Pet_Parent',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
