# Generated by Django 2.0.5 on 2018-06-05 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20180605_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet_Parent',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet_breed',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='pet_owner_interest_ref',
            name='interest_id',
        ),
        migrations.RemoveField(
            model_name='pet_owner_interest_ref',
            name='user',
        ),
        migrations.RemoveField(
            model_name='search',
            name='pet_breed_type',
        ),
        migrations.RemoveField(
            model_name='search',
            name='pet_type',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Pet_Breed',
        ),
        migrations.DeleteModel(
            name='Pet_Owner_Interest_Ref',
        ),
        migrations.DeleteModel(
            name='Pet_Owner_Interests',
        ),
        migrations.DeleteModel(
            name='Pet_Type',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
