# Generated by Django 2.0.5 on 2018-06-11 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=5, null=True)),
                ('special_inst', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_images')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_Breed', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('Add_Date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Breed added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Owner_Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest_Desc', models.CharField(max_length=60)),
                ('Add_Date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Owner Interest added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=30)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Type added')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_Date', models.DateTimeField(auto_now_add=True, verbose_name='Search Date')),
                ('zip_code', models.CharField(max_length=15)),
                ('pet_breed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pet_Breed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pet_Type')),
            ],
        ),
        migrations.AddField(
            model_name='pet_breed',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pet_Type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Pet_Breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pet_Type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
