# Generated by Django 2.0.5 on 2018-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180611_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_breed',
            name='body_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet_breed',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet_breed',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
