# Generated by Django 2.0.5 on 2018-06-14 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20180611_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_Owner_Interest_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pet_Owner_Interests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
