# Generated by Django 2.0.5 on 2018-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pet_owner_interest_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_owner_interest_ref',
            name='interest_id',
        ),
        migrations.AddField(
            model_name='pet_owner_interest_ref',
            name='interest_id',
            field=models.ManyToManyField(to='home.Pet_Owner_Interests'),
        ),
    ]
