# Generated by Django 2.0.5 on 2018-05-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetExtFam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=5, null=True)),
                ('special_inst', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_images')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
                ('pet_breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetExtFam.Pet_Breed')),
                ('pet_type', models.ForeignKey(default='Dog', on_delete=django.db.models.deletion.CASCADE, to='PetExtFam.Pet_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Owner_Interest_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Owner_Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest_Desc', models.CharField(max_length=60)),
                ('Pet_Breed', models.CharField(max_length=50)),
                ('Add_Date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Owner Interest added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='Illinois', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cell_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('own_a_pet', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=1, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Parent added')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Parent updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_Date', models.DateTimeField(auto_now_add=True, verbose_name='Search Date')),
                ('zip_code', models.CharField(max_length=15)),
                ('radius', models.CharField(max_length=5)),
                ('pet_breed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetExtFam.Pet_Breed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetExtFam.Pet_Type')),
            ],
        ),
        migrations.AddField(
            model_name='pet_owner_interest_ref',
            name='interest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetExtFam.Pet_Owner_Interests'),
        ),
        migrations.AddField(
            model_name='pet_owner_interest_ref',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
