# Generated by Django 2.0.5 on 2018-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetExtFam', '0003_auto_20180531_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_parent',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
