# Generated by Django 2.0.5 on 2018-05-31 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetExtFam', '0002_auto_20180521_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
